version: "3"

services:
  admin-front:
    build: .
    restart: always
    ports:
      - "4200:3000"
    env_file: .env.local
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

